const findAll = require('../../api/camps/findAll')
const findPopular = require('../../api/camps/findPopular')
const findUpcoming = require('../../api/camps/findUpcoming')
const findSingle = require('../../api/camps/findSingle')
const findAvailable = require('../../api/camps/findAvailable')
const addRegistered = require('../../api/camps/addRegistered')
const createCamp = require('../../api/camps/createCamp')
const updateCamp = require('../../api/camps/updateCamp')
const removeCamp = require('../../api/camps/removeCamp')
const registeredCamp = require('../../api/camps/registeredCamp')
const createUpComing = require('../../api/camps/createUpComing')
const updateRegistered = require('../../api/camps/updateRegistered')
const verifyToken = require('../../middlewares/verifyToken')
const verifyOrganizer = require('../../middlewares/verifyOrganizer')
const verifyProfessional = require('../../middlewares/verifyProfessional')
const verifyAdmin = require('../../middlewares/verifyAdmin')
const findUpComingSingle = require('../../api/camps/findUpComingSingle')
const addAttended = require('../../api/camps/addAttended')
const updateUpComingStatus = require('../../api/camps/updateUpComingStatus')
const updateUpComing = require('../../api/camps/updateUpComing')
const removeUpComingCamp = require('../../api/camps/removeUpComingCamp')
const updateCampParticipant = require('../../api/camps/updateCampParticipant')
const findAccepted = require('../../api/camps/findAccepted')
const updateAttendant = require('../../api/camps/updateAttendant')
const updateUpcomingCount = require('../../api/camps/updateUpcomingCount')
const router = require('express').Router()

router.get('/camps',findAll)
router.get('/popular-camps', findPopular)
router.get('/upcoming-camps', findUpcoming)
router.get('/available-camps', verifyToken, findAvailable)
router.get('/camp-details/:campId', findSingle)
router.post('/add-registered-camp', verifyToken, addRegistered)
router.post('/add-a-camp', verifyToken, verifyOrganizer, createCamp)
router.put('/update-camp/:campId', verifyToken, verifyOrganizer, updateCamp)
router.put('/update-camp-participant-count/:campId', updateCampParticipant)
router.delete('/delete-camp/:campId', verifyToken, verifyOrganizer, removeCamp)
router.get('/registered-camps', verifyToken, registeredCamp)
router.post('/add-upcoming-camp', verifyToken, verifyOrganizer, createUpComing)
router.put('/update-registered-camp/:campId', verifyToken, updateRegistered)
router.get('/upcoming-camp-details/:campId', findUpComingSingle)
router.put('/update-upcoming-camp-status/:campId', verifyToken, verifyOrganizer, updateUpComingStatus)
router.put('/update-upcoming-camp/:campId', verifyToken, verifyOrganizer, updateUpComing)
router.delete('/delete-upcoming-camp/:campId', verifyToken, verifyOrganizer, removeUpComingCamp)
router.post('/add-attendant-camp', verifyToken, addAttended)
router.get('/accepted-camps', verifyToken, findAccepted)
router.put('/update-attendant-camps-status/:campId', verifyToken, verifyOrganizer, updateAttendant)
router.put('/update-upcoming-camp-count/:campId', verifyToken, verifyOrganizer, updateUpcomingCount)

module.exports = router